-- ====================================================================
-- SUPABASE DATABASE SETUP SCHEMA
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/wrdiwitjacjombhcddue/sql/new
-- ====================================================================

-- 1. Create applicants table
CREATE TABLE IF NOT EXISTS public.applicants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT NOT NULL,
  address TEXT,
  district TEXT NOT NULL,
  state TEXT DEFAULT 'Kerala',
  education TEXT NOT NULL,
  work_type TEXT NOT NULL,
  experience_years INTEGER NOT NULL DEFAULT 0,
  skills TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.applicants ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow anonymous users to submit applications (INSERT)
CREATE POLICY "Allow public insert" ON public.applicants 
  FOR INSERT WITH CHECK (true);

-- 4. Policy: Allow authenticated admin users to read applications (SELECT)
CREATE POLICY "Allow authenticated read" ON public.applicants 
  FOR SELECT USING (auth.role() = 'authenticated');

-- 5. Policy: Allow authenticated admin users to update application status (UPDATE)
CREATE POLICY "Allow authenticated update" ON public.applicants 
  FOR UPDATE USING (auth.role() = 'authenticated');
